### ISSUE TITLE
Charts display issue

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokirjandus#176]
Parts of charts are hidden in case of wider bars:
![image](https://user-images.githubusercontent.com/14974887/161613753-e3c86fdb-76d5-47d1-a011-83e819107f7c.png)

**Comment by Erikdzo** [comment]
The problem is that the scales are hard-coded. This can be easily fixed manually, like in https://github.com/geocollections/geokirjandus/commit/6387bbdb8f3a4571058decd6c1d301a010197c9f#.In the future should probably come up with a automated solution.
