### ISSUE TITLE
Solr query: Missing fields/tables

### ISSUE THREAD

**Issue by Erikdzo** [geocollections/geokirjandus#2]
Solr does not have a way to query libraries and reference query does not have fields related to libraries.

Additionally reference query gives language and type as an id.

**Comment by ollehints** [comment]
Solr index for library created and can be queried (https://api.geocollections.info/solr/library/). Reference query will now return additional fields: 

- reference_language,
- reference_language_en,
- reference_lang,
- reference_type,
- reference_type_en,
- reference_ris_type,
- libraries

The latter field includes library IDs enclosed by |, e.g., https://api.geocollections.info/solr/reference/?q=libraries:*|4|*
But for some reasons some API calls like that get very slow.

**Comment by Erikdzo** [comment]
Solr reference query does not return the ids of localities associated with each reference.

**Comment by ollehints** [comment]
solr now returns: taxa, taxon_ids, locality_ids

**Comment by Erikdzo** [comment]
Solr fields taxa and taxon_ids are not in the same order. Same with localities and locality_ids.

**Comment by ollehints** [comment]
taxa/id and locality/id should be in the correct order; for locality names in English new field localities_en was added to the index.
