### ISSUE TITLE
Front page components

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokirjandus#21]
Main title: Eesti maapõue teavikute register / Estonian geological literature database
Probably no secondary title needed, but can be: geoloogia.info (instead of e-maapõu) in both languages

Search box should be activated by default so user can start typing / searching immediately.

Instead of two buttons we could have one [OTSI / SIRVI], [SEARCH / BROWSE]

Somewhere we should also put link to the book "Raukas & Teedumäe (eds), 1997: Geology and Mineral Resources of Estonia" which is accessible at https://geoloogia.info/geology/ Could be in the central text box too (from API). 

Below, the front page should be divided into three blocks:
- Statistics - solr / facet data shown as:
   - total number of records (is_estonian_reference=1)
   - number of records by decades, as line- or bar chart (cf turba.geoloogia.info for graph examples) 
   - publication types as pie chart
   - languages as pie chart
   - main keywords
- Static introduction coming from API: https://api.geocollections.info/page/75
- Last edited records (the existing block)

The footer should be in the bottom even if the other component will not fill entire page.

Solr facet query:
```
q=*
&rows=0
&fq=is_estonian_reference:1
&facet=on

&facet.query=keywords%3A*alusp%C3%B5hjageoloogia*
&facet.query=keywords%3A*paleontoloogia*
&facet.query=keywords%3A*kvaternaarigeoloogia*
&facet.query=keywords%3A*maavarad*
&facet.query=keywords%3A*h%C3%BCdrogeoloogia*
&facet.query=keywords:*ehitusgeoloogia*
&facet.query=keywords:*m%C3%A4endus*
&facet.query=keywords:*personaalia*
&facet.query=keywords:*kroonika*

&facet.field=reference_language
&facet.mincount=1

&facet.field=reference_type

&facet.range=year_numeric
&f.year_numeric.facet.range.start=1820
&f.year_numeric.facet.range.end=2021
&f.year_numeric.facet.range.gap=10
&f.year_numeric.facet.range.other=before
&f.year_numeric.facet.range.other=after
```

**Comment by Erikdzo** [comment]
Everything should be added since: https://github.com/geocollections/geokirjandus/commit/5ab0d0a3f3ef7e3c3331842e0c55605a697a949e
