### ISSUE TITLE
Check/add missing fields to reference detail view

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokirjandus#22]
Currently some fields are missing in detail view, for instance, title_original: https://geoloogia.info/reference/15377
The list of fields needs to be checked.

**Comment by Erikdzo** [comment]
Added fields:

- title_original
- author_original
- parent_reference
- book_translated
- book_original
- figures

Also found field number, but have no idea what it should represent.

**Comment by Erikdzo** [comment]
Added number field to citation
