### ISSUE TITLE
APA style problems

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokirjandus#24]
The APA style seems to have problems - for instance it capitalizes words in book titles but not reference titles - why is that: Barkla, H. (1935). The drumlins of Türi (Estonia). Tartu Ülikooli Juures Oleva Loodusuurijate Seltsi Aruanded, 42, 1–7. https://www.etera.ee/s/bXzlD4aEwr

Also APA seems to not include some important data, like Publisher and Publisher place.

**Comment by Erikdzo** [comment]
Publisher and publisher place have been added
