### ISSUE TITLE
Solr fq: query parameters case-sensitive

### ISSUE THREAD

**Issue by Erikdzo** [geocollections/geokirjandus#3]
Right now solr fq: parameters are case-sensitive

### Example

* query1 : [https://api.geocollections.info/solr/reference/?start=0&rows=50&sort=id%20desc&defType=edismax&fq=author:*hints*](https://api.geocollections.info/solr/reference/?start=0&rows=50&sort=id%20desc&defType=edismax&fq=author:*hints*
)
returns 0 results
* query2 : [https://api.geocollections.info/solr/reference/?start=0&rows=50&sort=id%20desc&defType=edismax&fq=author:*Hints*](https://api.geocollections.info/solr/reference/?start=0&rows=50&sort=id%20desc&defType=edismax&fq=author:*Hints*
)
returns 378 results

### Expected

Both queries should return same results

**Comment by ollehints** [comment]
Leave this for now - it is complicated to achieve all what we want as the LowerCaseFilterFactory does not work with wildcards, we would need to change data types and duplicating all fields looks also bad idea...
Just the user should be warned - we need search tips section / popup (content could come from API).
