### ISSUE TITLE
Additional styles

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokirjandus#30]
Additional citation styles:
Geology: https://www.zotero.org/styles/geology
Geol Mag: https://www.zotero.org/styles/geological-magazine
Holocene: https://www.zotero.org/styles/the-holocene
Nature: https://www.zotero.org/styles/nature
Palaeo3: https://www.zotero.org/styles/palaeogeography-palaeoclimatology-palaeoecology

**Comment by Erikdzo** [comment]
Added: Geol Mag, Holocene and Nature. Check if they are correctly displayed.

With Geology and Palaeo3 errors were thrown. Seems like files describing those citations contain links to parent citation styles that do not load for some reason.

For Geology the parent style is: http://www.zotero.org/styles/the-geological-society-of-america
and Palaeo3 parent style is: http://www.zotero.org/styles/elsevier-harvard

Could these styles used instead? Comparing Geology and Palaeo3 to their respective parent style, they seem to be the same.
