### ISSUE TITLE
Parent reference chapters

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokirjandus#35]
Parent references, like books with individual chapters or volumes with individual articles, may have linked 'daughter references'. These should be shown as in the old app ordered by page numbers, for instance https://geoloogia.info/reference/532.
A separate query to seek for chapters needs to be sent: https://api.geocollections.info/solr/reference/?fq=parent_reference_id:532&fl=id,author,title,pages&sort=pages_start%20ASC

**Comment by Erikdzo** [comment]
Added in commit: https://github.com/geocollections/geokirjandus/commit/a7ce9612c6a304817ff57a95d2adf06cae0812c1
