### ISSUE TITLE
Add KIK logo to the footer

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokirjandus#44]
Add logo of KIK to the footer (first logo from left):
`    <a href="https://kik.ee" target="_blank" rel="noopener"><img src="https://files.geocollections.info/img/kik_valge.png" alt="KIK" title="KIK" style="height: 60px; padding: 5px 10px 0 0;"></a> `

**Comment by Erikdzo** [comment]
Added: https://github.com/geocollections/geokirjandus/commit/af3a27e524f199dabafb3a327d6117c4832db080
