### ISSUE TITLE
Estonian author/literature in detail view

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokirjandus#51]
In reference detail view it should be apparent to the user that it belongs to Estonian reference and Estonian author.
The easiest way would be to have two additional rows in the end of general info table, to be shown only if is_estonian_reference:1 and is_estonian_author:1: 
Eesti kirjandus | jah
Eesti autor | jah

**Comment by Erikdzo** [comment]
Added: https://github.com/geocollections/geokirjandus/commit/536ea056850665836e4f781d7cb83f27c3841495
