### ISSUE TITLE
Add edit button to reference detail view

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokirjandus#62]
Add links to https://edit.geocollections.info/reference/$reference_id and https://edit.geocollections.info/library/$library_id to reference and library detail pages.
Could be chips, similar to pdf/doi/url links, on the same row, but aligned to right and different color (dark orange with white text like in case of active page number chip).

**Comment by Erikdzo** [comment]
Added in https://github.com/geocollections/geokirjandus/commit/124e582be6246c4d520f91006496d14837b8a106
